# This is a basic workflow to help you get started with Actions

name: deploy-on-k8s

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a single command using the runners shell
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group list

      - name: Install kubectl 
        uses: azure/setup-kubectl@v3
        with:
          version: v1.25.2 # default is latest stable
        id: install

      - name: Set kubectl context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
          resource-group: 'dip-github-actions-rg'
          cluster-name: 'dip-dev-k8s'
        id: login
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
